export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const FETCH_CHANNEL = 'FETCH_CHANNEL';
export const EDIT_CHANNEL = 'EDIT_CHANNEL';
export const NEW_CHANNEL = 'NEW_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';

export const ERROR_FETCH_CHANNELS = 'ERROR_FETCH_CHANNELS';
export const ERROR_FETCH_CHANNEL = 'ERROR_FETCH_CHANNEL';
export const ERROR_NEW_CHANNEL = 'ERROR_NEW_CHANNEL';
export const ERROR_EDIT_CHANNEL = 'ERROR_EDIT_CHANNEL';
export const ERROR_DELETE_CHANNEL = 'ERROR_DELETE_CHANNEL';

export const UPDATE_AUTH2 = 'UPDATE_AUTH2';
